### ISSUE TITLE
nie moge dodac produktu

### ISSUE THREAD

**Issue by kijek** [arborQ/MyTargetPoC#20]
dla takich ustawien jak ponizej nie moge dodac produktu - nie wiem czemu 
![image](https://cloud.githubusercontent.com/assets/16573177/12353087/de09c56a-bb8b-11e5-904f-2f397920f697.png)

**Comment by kijek** [comment]
dalem krotszy kod i poszlo - jest jakis limit?
![image](https://cloud.githubusercontent.com/assets/16573177/12353123/1a92796e-bb8c-11e5-8138-cf58eadd1862.png)

**Comment by arborQ** [comment]
dopasowałem limity do tych na bazie danych.

**Comment by kijek** [comment]
? :)

2016-01-18 11:52 GMT+01:00 arborQ notifications@github.com:
